name: 'CI: Test ci-test-spack-package action'

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:
  schedule:
    - cron: '0 0 23 * *'

jobs:
  test-action:
    name: Test ci-test-spack-package action
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout action repository
        uses: actions/checkout@v4
        with:
          path: action
      
      - name: Checkout test package (w3emc)
        uses: actions/checkout@v4
        with:
          repository: NOAA-EMC/NCEPLIBS-w3emc
          path: test-package
      
      - name: Test action with w3emc package
        uses: ./action
        with:
          package-name: w3emc
          package-version: develop
          repo-dir: ${{ github.workspace }}/test-package
          parallel-jobs: 2
          spack-compiler: gcc@13
